language: node_js
script: make test-sauce
node_js:
- 0.11
env:
  global:
  - secure: BXiwf6TuOhuAX2YP/jWl/YToDwQ72Rl0ZEZS9BUxc0u70nhpY/e2xuWCqE8EcUbRIyW+aXQOcA7C6YziirC6SsQW38+S8HPpGGlk8X0yfqUMZvH/l3THpL9mntzFMJeBiFafF5O8oe9hwI+qDElxwB7lZlr0oKoOnj6ap4VDSHg=
  - secure: Tz+y9UDyzaQE/JRUmpfwIqEiFwnK009xEWS3tYQAf9sqragP6Sq3vVN/O8nmrGTDfKA0A77V/zm4Q9Ln/AIDwZxvF29T9NQT3sTL6QFAWp/O4jFWrvqirZ7Ksp1KIlTriCbmIfzXKTMuQVw2iy2g2VDP13Y1olutoY+5+nbPAZE=
  - secure: UB13Bs1oX1DMA3f7kkxKUVxZl84E2ebn58PWMCO09ZL0Wt4CIKsOPB2lKbIyssG4vIDpJpRkZjE1pWOY7mfmF5W0rHfxCEFML3QciygRBSgopmeHMnIBCXYXCD48iz4f6BhbaKfBXqQPXkLS5lDN/zKkgiULwuyLYqqAJDMbevs=
  - secure: JLZTvjBlWQHQ49T5EDb0ZWq7EG6c+6P5d+sPnPEE9lIlPy/POLEiIi/9gEtkYKHUcrzcSLIIzMeNcwbY6Ju2pWjxlcaD7ri/gRc+tgizSyB+8a9eueu5qM1BAa0PuLsi3mQspuB8NdX6iosGtmlZkJKiF12PY9HFuElz8SqDouI=
  matrix:
  - browser=safari
  - browser=firefox
  - browser=chrome
  - browser=ie11
  - browser=ie10
  - browser=ie9
  - browser=ie8
